*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/
*/1 * * * * sleep 2 && chmod -R 777 /Data/www/www.guizhou.com/adm/public/